#!/bin/bash
# 
# Filename: pe-add-group
# Created: Wed Jul  8 19:12:10 2015 (+1000)
# Version: 0.1.0
# Author: Ade
# Description: 
#   add a group under <parent>

# Change Log:
# 

HOST=$(grep server /etc/puppetlabs/puppet/classifier.yaml|awk '{print $2}')
PORT=$(grep port /etc/puppetlabs/puppet/classifier.yaml|awk '{print $2}')
 
CURLCERT="--cert /etc/puppetlabs/puppet/ssl/certs/${HOST}.pem --key /etc/puppetlabs/puppet/ssl/private_keys/${HOST}.pem --cacert /etc/puppetlabs/puppet/ssl/certs/ca.pem"
ENDPOINT="https://${HOST}:${PORT}/classifier-api/v1"

if [ $# -ne 2 ]; then
  echo "usage: $(basename $0) <parentid> <group>"
  exit 0
fi

sudo curl -s -X POST -H 'Content-Type: application/json' ${CURLCERT} -d \
  '{ "name": "'$2'", "parent": "'$1'", "environment": "production", "classes": {} }' ${ENDPOINT}/groups | jq .
