#!/bin/bash
# 
# Filename: pe-get-groupid
# Created: Wed Jul  8 19:11:37 2015 (+1000)
# Version: 0.1.0
# Author: Ade
# Description: 
#   gets a named groups uuid

# Change Log:
# 

HOST=$(grep server /etc/puppetlabs/puppet/classifier.yaml|awk '{print $2}')
PORT=$(grep port /etc/puppetlabs/puppet/classifier.yaml|awk '{print $2}')
 
CURLCERT="--cert /etc/puppetlabs/puppet/ssl/certs/${HOST}.pem --key /etc/puppetlabs/puppet/ssl/private_keys/${HOST}.pem --cacert /etc/puppetlabs/puppet/ssl/certs/ca.pem"
ENDPOINT="https://${HOST}:${PORT}/classifier-api/v1"

sudo curl -s ${ENDPOINT}/groups -H 'Content-Type: application/json' \
  ${CURLCERT} | jq '.[] | {name: .name, id: .id}' | \
  grep -B1 "\"name\": \"$1\"" | head -1 | awk -F'"' '{print $4}'
