#!/bin/bash
# 
# Filename: pe-update-classes
# Created: Wed Jul  8 19:08:01 2015 (+1000)
# Version: 0.1.0
# Author: Ade
# Description: 
#   updates console classes

# Change Log:
# 

HOST=$(grep server /etc/puppetlabs/puppet/classifier.yaml|awk '{print $2}')
PORT=$(grep port /etc/puppetlabs/puppet/classifier.yaml|awk '{print $2}')
 
CURLCERT="--cert /etc/puppetlabs/puppet/ssl/certs/${HOST}.pem --key /etc/puppetlabs/puppet/ssl/private_keys/${HOST}.pem --cacert /etc/puppetlabs/puppet/ssl/certs/ca.pem"
ENDPOINT="https://${HOST}:${PORT}/classifier-api/v1"

sudo curl -s -X POST -H 'Content-Type: application/json' ${CURLCERT} \
  ${ENDPOINT}/update-classes
